[package]
name = "package"
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook = "0.4.44"
mdbook-admonish = "1.18.0"
mdbook-footnote = "0.1.1"
mdbook-linkcheck = "0.7.7"
mdbook-mermaid = "0.14.1"
mdbook-pdf = "0.1.10"
mdbook-toc = "0.14.2"
